### ISSUE TITLE
Why do we delete the LNGS copy with os.remove instead of through rucio?

### ISSUE THREAD

**Issue by ershockley** [XENONnT/admix#24]
@lucascottolavina after something in the logs caught my eye I looked into the `clean_eb` task and noticed this: 

https://github.com/XENONnT/admix/blob/master/admix/tasks/clean_eb.py#L289

After removing the LNGS rule we then do os.remove to remove all file replicas. But rucio should do this automatically right? I'm just wondering why we include this step.

**Comment by lucascottolavina** [comment]
Because in the past the Rucio reaper was not doing it. We discussed it also with Rucio experts. They suggested to use the reaper2 instead of reaper but still Rucio server was not deleting them (it deletes the rule but not the files). A possible explanation could be that at that time we were massively removing a lot of rules from Nickhef and the reaper was so busy to not follow all delete requests. But we haven't demonstrated it and the reason is unexplained. Given that Rucio does not complain if you remove these files from your own before it, I prefer to keep this direct removal, in case this issue happens again. Also, even if Rucio reaper works reliably, the deletion delay could be up to 12 hours (let's remind that the 1-hour deadline rule deletion does not apply to the real deletion of the files, since this is done by another Rucio daemon, the reaper). In case of a strong DAQ activity, 12 hours of delayed removal could be very annoying since it could means several TBs occupied). As soon as this direct admix deletion does not creates problems to Rucio operations (it should be not), I would prefer to keep it.

**Comment by ershockley** [comment]
Ok makes sense, we are seeing the same problem on UC_OSG_USERDISK (data not being deleted) which is why I'm curious. 

I definitely agree to keep it here, but we really need to figure this out in the long term I think. This is a pretty crucial part of rucio that's just not working at the moment. 

Pascal and Judith are in contact with rucio devs about trying to understand the problem. Will keep you posted.
